### ISSUE TITLE
README clutter

### ISSUE THREAD

**Issue by peisenha** [eisenhauerIO/bibliography#8]
Please remove the clutter from the bottom of the README.md file

**Comment by DennisKubitza** [comment]
Already done by Benedikt in the branch intertemproal_altruism. We need to pull a second time. Sorry for the mistake: I thought these were Jabref commands and appeared in the documentation in the context of: 

This will create the keys automatically and in compliante with the oteher entries in litertue bib: <<<<< Head ...
